### PR TITLE
Create a real UMD script

### PR DESCRIPTION
**Pull request by ZsharE**
- Browserify package was installed
- a real UMD script was created

### CODE REVIEW

**Comment by mathieumagalhaes** [comment]
As this is basically just a dependency change, could you explain to me the benefit of this compared to the currently implemented UMD package?

**Comment by ZsharE** [comment]
The current UMD package cannot be loaded in the browser.

There is an open issue in the original repository that addresses this issue here: 
https://github.com/se-panfilov/jsvat/issues/105

I also changed the build:umd script in the package.json file.

**Comment by mathieumagalhaes** [comment]
> The current UMD package cannot be loaded in the browser.
> 
> There is an open issue in the original repository that addresses this issue here: [se-panfilov#105](https://github.com/se-panfilov/jsvat/issues/105)
> 
> I also changed the build:umd script in the package.json file.

Thanks for clarifying.
Could you provide a simple index.html with a simple example in, such that this can be tested for this PR and in the future aswell please ?

**Comment by ZsharE** [comment]
Test page added.

**Comment by mathieumagalhaes** [comment]
I've added your changes but your yarn.lock file still had remainders of your attempt from PR #11 

For some reason my editor created a new PR (PR #13).
I've used PR #13 to merge this in, and gave you credit there.
I've also linked back to this PR.

Thank you for your contribution! 🚀

**Comment by mathieumagalhaes** [comment]
@ZsharE Forgot to publish a new version on npm, which I have done so just now

**Pull request closed without merging**
